In [1]:
import numpy as np

In [2]:
# array
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [5]:
arr.ndim

1

In [6]:
arr.shape

(3,)

In [7]:
arr.size

3

In [8]:
arr.dtype

dtype('int32')

In [9]:
arr = np.array([[1,2,3],[4,5,6]])

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr.shape

(2, 3)

In [12]:
arr.size

6

In [13]:
arr.ndim

2

In [14]:
arr.dtype

dtype('int32')

In [15]:
arr = np.array([[[1,2,3],[89,67,2],[34,56,9]]])

In [16]:
arr

array([[[ 1,  2,  3],
        [89, 67,  2],
        [34, 56,  9]]])

In [17]:
arr.ndim

3

In [18]:
arr.shape

(1, 3, 3)

In [19]:
arr.size

9

In [20]:
arr

array([[[ 1,  2,  3],
        [89, 67,  2],
        [34, 56,  9]]])

In [26]:
arr[0][2][1]=90

In [27]:
arr

array([[[ 1,  2,  3],
        [89, 67,  2],
        [34, 90,  9]]])

In [68]:
# max
# min
# sum
# axis

x = np.array([[23,90,-4],[67,3,45]])

In [30]:
x

array([[23, 90, -4],
       [67,  3, 45]])

In [31]:
x.max()

90

In [32]:
x.min()

-4

In [33]:
x.sum()

224

In [34]:
x.sum(axis = 0)

array([90, 93, 41])

In [35]:
x.sum(axis =1)

array([109, 115])

In [36]:
# ones
# zeros
# empty
# linspace
# transpose
# identity



In [42]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
np.ones([5,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
np.ones([5],[2])

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [46]:
np.ones([[5,3],[2,5]])

TypeError: 'list' object cannot be interpreted as an integer

In [47]:
np.ones([[5,2]])

TypeError: 'list' object cannot be interpreted as an integer

In [49]:
np.ones([5,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
np.zeros(4)

array([0., 0., 0., 0.])

In [56]:
np.empty((1,3))

array([[6.94005757e-312, 0.00000000e+000, 1.11259601e-306]])

In [60]:
np.linspace(1,6,30)

array([1.        , 1.17241379, 1.34482759, 1.51724138, 1.68965517,
       1.86206897, 2.03448276, 2.20689655, 2.37931034, 2.55172414,
       2.72413793, 2.89655172, 3.06896552, 3.24137931, 3.4137931 ,
       3.5862069 , 3.75862069, 3.93103448, 4.10344828, 4.27586207,
       4.44827586, 4.62068966, 4.79310345, 4.96551724, 5.13793103,
       5.31034483, 5.48275862, 5.65517241, 5.82758621, 6.        ])

In [64]:
# arange
np.arange(3,50,4)

array([ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47])

In [67]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [74]:
x = np.array([[[23,34,6],[89,56,3],[25,80,4]]])

In [75]:
x

array([[[23, 34,  6],
        [89, 56,  3],
        [25, 80,  4]]])

In [77]:
x.T

array([[[23],
        [89],
        [25]],

       [[34],
        [56],
        [80]],

       [[ 6],
        [ 3],
        [ 4]]])

In [76]:
x

array([[[23, 34,  6],
        [89, 56,  3],
        [25, 80,  4]]])

In [78]:
x = np.array([[1,4,7],[89,3,6]])

In [79]:
x

array([[ 1,  4,  7],
       [89,  3,  6]])

In [80]:
x.T

array([[ 1, 89],
       [ 4,  3],
       [ 7,  6]])

In [81]:
# sort
x.sort()

In [82]:
x

array([[ 1,  4,  7],
       [ 3,  6, 89]])

In [83]:
# argmax,argmin,argsort
x.argmax()

5

In [84]:
x.argmin()

0

In [85]:
x.argsort()

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)