In [9]:
a = [34,78,90,23]
b = [56,67,99,780]

for i in a:
    for j in b:
        if i == j :
            print("Common element",i)
else:
    print("NC")

NC


In [2]:
type(i)

int

In [10]:
# identity matrix
# Transpose 

# 1d data 3*3 matrix
# 2d 


import numpy as np

In [34]:
arr = np.array([[34,45,56],[45,90,87],[67,45,12]])

In [12]:
arr

array([[34, 45, 56],
       [45, 90, 87],
       [67, 45, 12]])

In [13]:
# Transpose

arr.T

array([[34, 45, 67],
       [45, 90, 45],
       [56, 87, 12]])

In [19]:
# identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Aggregation  functions

In [20]:
arr

array([[34, 45, 56],
       [45, 90, 87],
       [67, 45, 12]])

In [21]:
arr.max()

90

In [22]:
arr.min()

12

In [25]:
arr.mean()

53.44444444444444

In [27]:
arr

array([[34, 45, 56],
       [45, 90, 87],
       [67, 45, 12]])

# arg max/argmin

In [28]:
arr

array([[34, 45, 56],
       [45, 90, 87],
       [67, 45, 12]])

In [29]:
arr.argmax()

4

In [30]:
arr.argmin()

8

In [31]:
arr

array([[34, 45, 56],
       [45, 90, 87],
       [67, 45, 12]])

In [32]:
arr.sort()

In [33]:
arr

array([[34, 45, 56],
       [45, 87, 90],
       [12, 45, 67]])

In [35]:
arr.argsort()

array([[0, 1, 2],
       [0, 2, 1],
       [2, 1, 0]], dtype=int64)