In [1]:
# Numpy ----> it a mathematical lib.

import numpy as np

In [16]:
# Array -----> list


arr = np.array([1,2,3,4])

In [17]:
arr

array([1, 2, 3, 4])

In [18]:
arr.shape

(4,)

In [19]:
arr.ndim

1

In [20]:
type(arr)

numpy.ndarray

In [21]:
arr.size

4

In [35]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [36]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
arr.ndim

2

In [38]:
arr.shape

(2, 4)

In [26]:
arr.size

8

In [40]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [41]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [42]:
arr.shape

(1, 3, 3)

In [43]:
# exp.

arr = np.array([1,2,'hello'])

In [44]:
arr

array(['1', '2', 'hello'], dtype='<U11')

In [46]:
arr.dtype

dtype('<U11')

In [47]:
arr.shape

(3,)

In [49]:
arr.size

3

In [50]:
arr.ndim

1