In [1]:
import numpy as np

In [2]:
# arrays
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
arr.dtype

dtype('int32')

In [5]:
arr.shape

(4,)

In [6]:
arr.size

4

In [7]:
arr.ndim

1

In [8]:
arr = np.array([[1,2,3],[4,5,6]])

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr.ndim

2

In [11]:
arr.shape

(2, 3)

In [12]:
arr.size

6

In [13]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [14]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
arr.ndim

3

In [16]:
arr.shape

(1, 3, 3)

In [17]:
arr.size

9

In [46]:
#wap to make 3d matrix?

arr = np.array([[[34,67,89],[90,56,23],[67,45,13]]])

In [19]:
arr

array([[[34, 67, 89],
        [90, 56, 23],
        [67, 45, 13]]])

In [20]:
arr = np.array([[[1,2,3]]])

In [21]:
arr

array([[[1, 2, 3]]])

In [22]:
arr.shape

(1, 1, 3)

In [23]:
arr.size

3

In [25]:
arr = np.array([[1,2,3],[56,89,-90]])

In [26]:
arr

array([[  1,   2,   3],
       [ 56,  89, -90]])

In [28]:
arr

array([[[34, 67, 89],
        [90, 56, 23],
        [67, 45, 13]]])

In [37]:
arr[0][0][1]

67

In [41]:
arr = np.array([[3,5,6]])

In [42]:
arr

array([[3, 5, 6]])

In [45]:
arr[0][1]

5

In [47]:
arr

array([[[34, 67, 89],
        [90, 56, 23],
        [67, 45, 13]]])

In [50]:
arr[0][0][1]

67

In [53]:
arr[0][1][1]

56

In [54]:
arr[0][2][0]

67

In [57]:
# sum 
a= arr.sum()

In [58]:
a

484

In [60]:
arr = np.array([[[1,2,3],[4,5,6],[6,7,8]]])

In [61]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]])

In [62]:
x = arr.sum()

In [63]:
x

42

In [64]:
6+15+21

42

In [65]:
arr.sum(axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [66]:
arr.sum(axis = 1)

array([[11, 14, 17]])

In [68]:
arr = np.array([[[1,2,3]]])

In [69]:
arr.sum(axis = 0)

array([[1, 2, 3]])

In [70]:
arr.sum(axis = 1)

array([[1, 2, 3]])

In [75]:
# 3*3 matrix


# zeros & ones
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [77]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [80]:
# arange
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [81]:
np.arange(3,21)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [82]:
np.arange(6,61,2)

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38,
       40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [88]:
# empty
# linespace

np.empty(2)

array([1.04244725e-311, 4.94065646e-324])

In [91]:
np.empty((2,5))

array([[4.67296746e-307, 1.69121096e-306, 1.78019082e-306,
        6.23057688e-307, 2.22526399e-307],
       [6.23053614e-307, 7.56592338e-307, 9.34588061e-307,
        1.86918699e-306, 1.02356521e-306]])

In [99]:
np.linspace(1,10,60)

array([ 1.        ,  1.15254237,  1.30508475,  1.45762712,  1.61016949,
        1.76271186,  1.91525424,  2.06779661,  2.22033898,  2.37288136,
        2.52542373,  2.6779661 ,  2.83050847,  2.98305085,  3.13559322,
        3.28813559,  3.44067797,  3.59322034,  3.74576271,  3.89830508,
        4.05084746,  4.20338983,  4.3559322 ,  4.50847458,  4.66101695,
        4.81355932,  4.96610169,  5.11864407,  5.27118644,  5.42372881,
        5.57627119,  5.72881356,  5.88135593,  6.03389831,  6.18644068,
        6.33898305,  6.49152542,  6.6440678 ,  6.79661017,  6.94915254,
        7.10169492,  7.25423729,  7.40677966,  7.55932203,  7.71186441,
        7.86440678,  8.01694915,  8.16949153,  8.3220339 ,  8.47457627,
        8.62711864,  8.77966102,  8.93220339,  9.08474576,  9.23728814,
        9.38983051,  9.54237288,  9.69491525,  9.84745763, 10.        ])

In [110]:
#wap to print the common element.
x = [23,45,89,34]
y = [78,86,45,23]
z = [67,23,71,45]

for kamal in x:
    for j in y:
        for k in z:
            if kamal == j and j == k:
                print("Common elements------>",j)

Common elements------> 23
Common elements------> 45
